/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package globalhome;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author eliss
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();

      this.setLocationRelativeTo(null);		
      this.setVisible(true);
        
        
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/registro.jpg"));
        Icon fondo1 =new ImageIcon(imagen1.getImage().getScaledInstance(I.getWidth(),I.getHeight(),Image.SCALE_DEFAULT));
        I.setIcon(fondo1);
        this.repaint();
       
        this.setTitle("GLOBAL HOME");
        this.setLocationRelativeTo(Registrarse.this);
        this.setExtendedState(WIDTH);
        Image ico= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/escudo_fi_color.png"));
        this.setIconImage(ico);
        
        this.setSize(new Dimension(1340, 860));
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarse1 = new javax.swing.JButton();
        registrarse = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        ap_pat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ap_mat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        I = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        registrarse1.setBackground(new java.awt.Color(255, 204, 255));
        registrarse1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        registrarse1.setText("Guardar");
        registrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarse1ActionPerformed(evt);
            }
        });
        getContentPane().add(registrarse1);
        registrarse1.setBounds(280, 630, 230, 110);

        registrarse.setBackground(new java.awt.Color(255, 204, 255));
        registrarse.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        registrarse.setText("Home");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(registrarse);
        registrarse.setBounds(710, 630, 230, 110);

        nombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(nombre);
        nombre.setBounds(820, 160, 430, 50);

        usuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(usuario);
        usuario.setBounds(160, 160, 430, 50);

        email.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(email);
        email.setBounds(150, 320, 430, 50);

        pass.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(150, 470, 430, 50);

        ap_pat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(ap_pat);
        ap_pat.setBounds(830, 310, 430, 50);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 74, 84));
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 400, 220, 60);

        ap_mat.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        getContentPane().add(ap_mat);
        ap_mat.setBounds(830, 470, 430, 50);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(246, 74, 84));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 160, 60);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(246, 74, 84));
        jLabel4.setText("Apellido Materno ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 380, 430, 60);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 74, 84));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 230, 160, 60);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(246, 74, 84));
        jLabel5.setText("Nombre ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 70, 160, 60);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(246, 74, 84));
        jLabel6.setText("Apellido Paterno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 230, 300, 60);
        getContentPane().add(I);
        I.setBounds(0, 0, 1320, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        Registrarse r=new Registrarse();
        r.setVisible(true);
        toFront();
        this.dispose();
    }//GEN-LAST:event_registrarseActionPerformed

    private void registrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarse1ActionPerformed
        Registrarse r=new Registrarse();
        r.setVisible(true);
        toFront();
        this.dispose();
    }//GEN-LAST:event_registrarse1ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel I;
    private javax.swing.JTextField ap_mat;
    private javax.swing.JTextField ap_pat;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pass;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton registrarse1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
